### ISSUE TITLE
Internal 500 Error on "page:2" and tag URLs

### ISSUE THREAD

**Issue by sqdge** [sashtown/baseblog#12]
I have set up baseblog on a subfolder at http://localhost/bg. My .htaccess file has:
    `RewriteEngine on`
    `RewriteBase /bg`

Additionally, the config.php file is set to:
    `c::set('url', 'http://localhost/bg');`
    `c::set('subfolder', 'bg');`

Most of the rewriting works fine. The main blog page comes up and I can click on and access any of the posts and pages. However, if I click on the "older posts" button I get an internal server error. It is directing me to the url `http://localhost/bg/page:2`. Similarly, clicking on a tag in the post produces the same error. The URL for those is `http://localhost/bg/tag:nature`

The Appache Error log says:
>AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://localhost/bg/

Any ideas?

**Comment by sashtown** [comment]
Did you try it **without** adjusting the RewriteBase and config? Since version 2 Kirby is able to detect subfolder installations automatically. Never had problems with that so far. The [Baseblog demo] (<http://baseblog.sashtown.de/demo/>) also runs in a subfolder without any additional tweaks.

**Comment by labo-css** [comment]
Same problem here, i work with wamp.

**Comment by sashtown** [comment]
Ok, I see. There (still) seems to be [an issue](https://github.com/getkirby/kirby/issues/101) with `:` characters within URLs on Apache servers on Windows. That’s why I wasn't able to retrace that error, because I work on a Mac. Had a quick chat with Bastian a few days ago. It should be fixed in the frontend with the latest Kirby version, so please make sure to get 2.1.1. If you face problems again, please open an issue in the [Kirby repo](https://github.com/getkirby/kirby/issues).

**Comment by labo-css** [comment]
I did get the 2.1.1 you mean : "get the next version, it should be done for the next patch of kirby"?
(sorry i don't want to be sarcastic or anything, i'm french and i just want to be sure to understand, thanx)

**Comment by sashtown** [comment]
Yeah, no problem. If you still run into trouble, please open an issue [here](https://github.com/getkirby/kirby/issues) and provide as much information about your setup as possible. Thanks!
