### ISSUE TITLE
New install shows Forbidden for Category Search

### ISSUE THREAD

**Issue by username1290** [sashtown/baseblog#8]
Hi, installed on a local server and everything works great except clicking on a Category.
Error shows:

Forbidden
You don't have permission to access /kirbybaseblog/category:Tools on this server.

btw, troubleshoot set to true also says that default.php template was not found, but I think that's on purpose, right?

thx.

EDIT: Tried adding +Indexes to htaccess but no luck

**Comment by frenchesco** [comment]
I realize this issue is closed, however, it still seems to be happening. I did some reading and I think it might have something to do with having a colon `:` character in the URL when running on Windows. This is likely because Windows does not allow colon characters in a file name. For me it was happening when running a local WAMP server.

**Comment by sashtown** [comment]
@frenchesco Yes, you're right. Please also check: https://github.com/sashtown/baseblog/issues/12.

**Comment by frenchesco** [comment]
@sashtown Thanks for the update. Glad it's getting fixed. I've since switched to testing locally on my Mac with MAMP and will eventually deploy to a Ubuntu server so should all be ok.
